#ifndef __TEMPERATURE_H__
#define __TEMPERATURE_H__

/* Configuration Register */
#define CONFIG_SHUTDOWN_MODE_DISABLE		0x00
#define CONFIG_SHUTDOWN_MODE_ENABLE			0x01
#define CONFIG_THERMOSTAT_MODE_DISABLE		0x00
#define CONFIG_THERMOSTAT_MODE_ENABLE		0x02
#define CONFIG_POLARITY_DISABLE				0x00
#define CONFIG_POLARITY_ENABLE				0x04
#define CONFIG_FAULT_QUEUE_1				0x00
#define CONFIG_FAULT_QUEUE_2				0x08
#define CONFIG_FAULT_QUEUE_4				0x10
#define CONFIG_FAULT_QUEUE_6				0x18
#define CONFIG_CONVERTER_RESOLUTION_9BIT	0x00
#define CONFIG_CONVERTER_RESOLUTION_10BIT	0x20
#define CONFIG_CONVERTER_RESOLUTION_11BIT	0x40
#define CONFIG_CONVERTER_RESOLUTION_12BIT	0x60
#define CONFIG_ONE_SHOT_DISABLE				0x00
#define CONFIG_ONE_SHOT_ENABLE				0x80

#define CONFIG_SHUTDOWN_MODE				CONFIG_SHUTDOWN_MODE_ENABLE
#define CONFIG_THERMOSTAT_MODE				CONFIG_THERMOSTAT_MODE_DISABLE
#define CONFIG_POLARITY						CONFIG_POLARITY_DISABLE
#define CONFIG_FAULT_QUEUE					CONFIG_FAULT_QUEUE_1
#define CONFIG_CONVERTER_RESOLUTION			CONFIG_CONVERTER_RESOLUTION_9BIT
#define CONFIG_ONE_SHOT						CONFIG_ONE_SHOT_DISABLE

#define CONFIG_DEFAULT						(CONFIG_SHUTDOWN_MODE |\
											 CONFIG_THERMOSTAT_MODE |\
											 CONFIG_POLARITY |\
											 CONFIG_FAULT_QUEUE |\
											 CONFIG_CONVERTER_RESOLUTION |\
											 CONFIG_ONE_SHOT)

/* 温度計算用定数 */
/* CONFIG_CONVERTER_RESOLUTION_9BIT用 */
#define TEMP_REG_RES9_BYTE1_LSHIFT		1
#define TEMP_REG_RES9_BYTE2_RSHIFT		7
#define TEMP_REG_RES9_BYTE2_MASK		0x80
#define TEMP_RES9_UNIT					(0.5f)		/* 0.5℃刻み */
/* CONFIG_CONVERTER_RESOLUTION_10BIT用 */
#define TEMP_REG_RES10_BYTE1_LSHIFT		2
#define TEMP_REG_RES10_BYTE2_RSHIFT		6
#define TEMP_REG_RES10_BYTE2_MASK		0xC0
#define TEMP_RES10_UNIT					(0.25f)		/* 0.25℃刻み */
/* CONFIG_CONVERTER_RESOLUTION_11BIT用 */
#define TEMP_REG_RES11_BYTE1_LSHIFT		3
#define TEMP_REG_RES11_BYTE2_RSHIFT		5
#define TEMP_REG_RES11_BYTE2_MASK		0xE0
#define TEMP_RES11_UNIT					(0.125f)	/* 0.125℃刻み */
/* CONFIG_CONVERTER_RESOLUTION_12BIT用 */
#define TEMP_REG_RES12_BYTE1_LSHIFT		4
#define TEMP_REG_RES12_BYTE2_RSHIFT		4
#define TEMP_REG_RES12_BYTE2_MASK		0xF0
#define TEMP_RES12_UNIT					(0.0625f)	/* 0.0625℃刻み */

#if (CONFIG_CONVERTER_RESOLUTION == CONFIG_CONVERTER_RESOLUTION_12BIT)
#define TEMP_REG_BYTE1_LSHIFT			TEMP_REG_RES12_BYTE1_LSHIFT
#define TEMP_REG_BYTE2_RSHIFT			TEMP_REG_RES12_BYTE2_RSHIFT
#define TEMP_REG_BYTE2_MASK				TEMP_REG_RES12_BYTE2_MASK
#define	TEMP_UNIT						TEMP_RES21_UNIT
#elif (CONFIG_CONVERTER_RESOLUTION == CONFIG_CONVERTER_RESOLUTION_11BIT)
#define TEMP_REG_BYTE1_LSHIFT			TEMP_REG_RES11_BYTE1_LSHIFT
#define TEMP_REG_BYTE2_RSHIFT			TEMP_REG_RES11_BYTE2_RSHIFT
#define TEMP_REG_BYTE2_MASK				TEMP_REG_RES11_BYTE2_MASK
#define	TEMP_UNIT						TEMP_RES11_UNIT
#elif (CONFIG_CONVERTER_RESOLUTION == CONFIG_CONVERTER_RESOLUTION_10BIT)
#define TEMP_REG_BYTE1_LSHIFT			TEMP_REG_RES10_BYTE1_LSHIFT
#define TEMP_REG_BYTE2_RSHIFT			TEMP_REG_RES10_BYTE2_RSHIFT
#define TEMP_REG_BYTE2_MASK				TEMP_REG_RES10_BYTE2_MASK
#define	TEMP_UNIT						TEMP_RES10_UNIT
#else	/* CONFIG_CONVERTER_RESOLUTION == CONFIG_CONVERTER_RESOLUTION_9BIT */
#define TEMP_REG_BYTE1_LSHIFT			TEMP_REG_RES9_BYTE1_LSHIFT
#define TEMP_REG_BYTE2_RSHIFT			TEMP_REG_RES9_BYTE2_RSHIFT
#define TEMP_REG_BYTE2_MASK				TEMP_REG_RES9_BYTE2_MASK
#define	TEMP_UNIT						TEMP_RES9_UNIT
#endif

/** 
 * @brief  Temperatureの初期化
 * @param  None
 * @return  None
 */
void temperature_init(void);

/** 
 * @brief  Temperature取得
 * @param  float temperature : 温度
 * @return  None
 */
float get_temperature(void);

#endif /* __TEMPERATURE_H__ */
